# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fc00cba1a3a020a5a1c8657cb7fadb20902ff93b3232e06671a3b297cc970d88ba3e354559a0f852ff953ffec0464ea0253a17ac3710eeecdd5bcd4ba1e98f0

test:
  secret_key_base: 975d9ec6cf306ac232872955e4e15cb7081b5d77374a06332bab46293ca3e8d4c1e52bc10ba0327738f431be4833d680a00cd074ba8c2df82fda0c3a94bc5681

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
